### ISSUE TITLE
Ordered Select Widget content disappear - bad <script> end tag

### ISSUE THREAD

**Issue by Martronic-SA** [zopefoundation/z3c.form#29]
It seems that the syntax
\<script type="text/javascript" src="++resource++orderedselect_input.js" />
used in orderedselect_input.pt is not correctly interpreted by the browser if the content header of the page is set to text/html.
You should use \<script type="text/javascript" src="++resource++orderedselect_input.js" ></script>
Otherwise the content of the widget disappears.
changes made in version 3.2.3

**Comment by petri** [comment]
Some discussion on the topic at SO: http://stackoverflow.com/questions/69913/why-dont-self-closing-script-tags-work

**Comment by mgedmin** [comment]
I thought zope.pagetemplate hardcoded the `<script>` tag handling to always generate `<script></script>`?  Are we accidentally using XML mode here?  Is the `<script>` tag generated by Python code and not a template?

I don't have time/inclination to look at this now, but if someone wants to investigate/submit a pull request, I'll try to help.

**Comment by petri** [comment]
Hm, I took a look and this seems to be fixed by @vangheem in ab2080a9cd69797167b09eb984787857bcc4d59e , for 3.2.4. Should be ok to close, AFAIK.

**Comment by vangheem** [comment]
Yes, this should be fixed in latest release.
