### ISSUE TITLE
headsup for MAJOR overhaul of ObjectWidget PR

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/z3c.form#40]
see #38 

please review or comment
when noone objects will merge in a week

**Comment by Martronic-SA** [comment]
collective.z3cform.datagridfield is broken by that commit.
I don't know if it will be possible to fix with thoses changes.. ?

**Comment by agroszer** [comment]
Sorry, ObjectWidget was PITA. You could pin z3c.form at a version that's compatible with collective.z3cform.datagridfield

**Comment by thet** [comment]
Shouldn't the general zopefoundation code review rules - getting review from another person - also apply to z3c.form?

Your self-merged changes for z3c.form 3.3.0 (should actually be a 4.0 release) introduces hard-to-resolve incompatibilities with Plone. And Plone is probably the biggest consumer of this project.

/cc @mgedmin @tseaver @esteele
