### ISSUE TITLE
Wrong version numbers.

### ISSUE THREAD

**Issue by jensens** [zopefoundation/z3c.form#41]
I really would love to see the maintainers of this package to stick to semantic versioning. For consumers of this package this would make live and management of their packages much easier.

This change 

```
* ``ObjectSubForm`` and ``SubformAdapter`` is removed,
    it was causing more problems than good
```

Would need a new major version number. 

For more information about semantic versioning please read carefully http://semver.org/

**Comment by icemac** [comment]
Fixed in the repos, now I have to cut releases.

**Comment by icemac** [comment]
I deleted the `3.2.x` branch in favour of the `3.x` branch.

**Comment by icemac** [comment]
Releases of both branches are now on PyPI, see https://pypi.org/project/z3c.form/#history
