### ISSUE TITLE
Time to release 3.4.0?

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/z3c.form#57]
Currently https://github.com/zopefoundation/z3c.formwidget.query is broken because of https://github.com/zopefoundation/z3c.form/commit/dd40f6f513b08854c64e8d59cf6440082f4b11d9 and needs the bugfix from https://github.com/zopefoundation/z3c.form/commit/b89f38f9ca4bf9e321b52c976d32c2db3cabaea7.

Does anyone have any objections to me (or, preferably, *somebody else*) releasing the current master as 3.4.0?

**Comment by mauritsvanrees** [comment]
I have released 3.2.11 (used by all current Plone versions) and 3.4.0.
